// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: chat_with_otomo_service.proto

package grpcgen

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatWithOtomoMessageToOtomoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ChatWithOtomoMessageToOtomoRequest) Reset() {
	*x = ChatWithOtomoMessageToOtomoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_with_otomo_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatWithOtomoMessageToOtomoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatWithOtomoMessageToOtomoRequest) ProtoMessage() {}

func (x *ChatWithOtomoMessageToOtomoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_with_otomo_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatWithOtomoMessageToOtomoRequest.ProtoReflect.Descriptor instead.
func (*ChatWithOtomoMessageToOtomoRequest) Descriptor() ([]byte, []int) {
	return file_chat_with_otomo_service_proto_rawDescGZIP(), []int{0}
}

func (x *ChatWithOtomoMessageToOtomoRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ChatWithOtomoMessageToOtomoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reply *MessageWithOtomo `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
}

func (x *ChatWithOtomoMessageToOtomoResponse) Reset() {
	*x = ChatWithOtomoMessageToOtomoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_with_otomo_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatWithOtomoMessageToOtomoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatWithOtomoMessageToOtomoResponse) ProtoMessage() {}

func (x *ChatWithOtomoMessageToOtomoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_with_otomo_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatWithOtomoMessageToOtomoResponse.ProtoReflect.Descriptor instead.
func (*ChatWithOtomoMessageToOtomoResponse) Descriptor() ([]byte, []int) {
	return file_chat_with_otomo_service_proto_rawDescGZIP(), []int{1}
}

func (x *ChatWithOtomoMessageToOtomoResponse) GetReply() *MessageWithOtomo {
	if x != nil {
		return x.Reply
	}
	return nil
}

var File_chat_with_otomo_service_proto protoreflect.FileDescriptor

var file_chat_with_otomo_service_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x6f, 0x74, 0x6f, 0x6d,
	0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x6f, 0x74, 0x6f, 0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x41, 0x0a, 0x22, 0x43, 0x68, 0x61, 0x74, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x74,
	0x6f, 0x6d, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x4f, 0x74, 0x6f, 0x6d,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x4e, 0x0a, 0x23, 0x43, 0x68, 0x61, 0x74, 0x57, 0x69, 0x74,
	0x68, 0x4f, 0x74, 0x6f, 0x6d, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x4f,
	0x74, 0x6f, 0x6d, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x05,
	0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x74, 0x6f, 0x6d, 0x6f, 0x52, 0x05,
	0x72, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x75, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x74, 0x57, 0x69, 0x74,
	0x68, 0x4f, 0x74, 0x6f, 0x6d, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a,
	0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x4f, 0x74, 0x6f, 0x6d, 0x6f, 0x12,
	0x23, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x74, 0x6f, 0x6d, 0x6f, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x4f, 0x74, 0x6f, 0x6d, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x57, 0x69, 0x74, 0x68, 0x4f,
	0x74, 0x6f, 0x6d, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x4f, 0x74, 0x6f,
	0x6d, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09,
	0x2e, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_chat_with_otomo_service_proto_rawDescOnce sync.Once
	file_chat_with_otomo_service_proto_rawDescData = file_chat_with_otomo_service_proto_rawDesc
)

func file_chat_with_otomo_service_proto_rawDescGZIP() []byte {
	file_chat_with_otomo_service_proto_rawDescOnce.Do(func() {
		file_chat_with_otomo_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_chat_with_otomo_service_proto_rawDescData)
	})
	return file_chat_with_otomo_service_proto_rawDescData
}

var file_chat_with_otomo_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chat_with_otomo_service_proto_goTypes = []interface{}{
	(*ChatWithOtomoMessageToOtomoRequest)(nil),  // 0: ChatWithOtomoMessageToOtomoRequest
	(*ChatWithOtomoMessageToOtomoResponse)(nil), // 1: ChatWithOtomoMessageToOtomoResponse
	(*MessageWithOtomo)(nil),                    // 2: MessageWithOtomo
}
var file_chat_with_otomo_service_proto_depIdxs = []int32{
	2, // 0: ChatWithOtomoMessageToOtomoResponse.reply:type_name -> MessageWithOtomo
	0, // 1: ChatWithOtomoService.MessageToOtomo:input_type -> ChatWithOtomoMessageToOtomoRequest
	1, // 2: ChatWithOtomoService.MessageToOtomo:output_type -> ChatWithOtomoMessageToOtomoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chat_with_otomo_service_proto_init() }
func file_chat_with_otomo_service_proto_init() {
	if File_chat_with_otomo_service_proto != nil {
		return
	}
	file_message_with_otomo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_chat_with_otomo_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatWithOtomoMessageToOtomoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_with_otomo_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatWithOtomoMessageToOtomoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chat_with_otomo_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_with_otomo_service_proto_goTypes,
		DependencyIndexes: file_chat_with_otomo_service_proto_depIdxs,
		MessageInfos:      file_chat_with_otomo_service_proto_msgTypes,
	}.Build()
	File_chat_with_otomo_service_proto = out.File
	file_chat_with_otomo_service_proto_rawDesc = nil
	file_chat_with_otomo_service_proto_goTypes = nil
	file_chat_with_otomo_service_proto_depIdxs = nil
}
