// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: chat_with_otomo_service.proto

package grpcgen

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on ChatWithOtomoMessageToOtomoRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ChatWithOtomoMessageToOtomoRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChatWithOtomoMessageToOtomoRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ChatWithOtomoMessageToOtomoRequestMultiError, or nil if none found.
func (m *ChatWithOtomoMessageToOtomoRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ChatWithOtomoMessageToOtomoRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetText()) < 1 {
		err := ChatWithOtomoMessageToOtomoRequestValidationError{
			field:  "Text",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ChatWithOtomoMessageToOtomoRequestMultiError(errors)
	}
	return nil
}

// ChatWithOtomoMessageToOtomoRequestMultiError is an error wrapping multiple
// validation errors returned by
// ChatWithOtomoMessageToOtomoRequest.ValidateAll() if the designated
// constraints aren't met.
type ChatWithOtomoMessageToOtomoRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChatWithOtomoMessageToOtomoRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChatWithOtomoMessageToOtomoRequestMultiError) AllErrors() []error { return m }

// ChatWithOtomoMessageToOtomoRequestValidationError is the validation error
// returned by ChatWithOtomoMessageToOtomoRequest.Validate if the designated
// constraints aren't met.
type ChatWithOtomoMessageToOtomoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChatWithOtomoMessageToOtomoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChatWithOtomoMessageToOtomoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChatWithOtomoMessageToOtomoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChatWithOtomoMessageToOtomoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChatWithOtomoMessageToOtomoRequestValidationError) ErrorName() string {
	return "ChatWithOtomoMessageToOtomoRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ChatWithOtomoMessageToOtomoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChatWithOtomoMessageToOtomoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChatWithOtomoMessageToOtomoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChatWithOtomoMessageToOtomoRequestValidationError{}

// Validate checks the field values on ChatWithOtomoMessageToOtomoResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ChatWithOtomoMessageToOtomoResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChatWithOtomoMessageToOtomoResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ChatWithOtomoMessageToOtomoResponseMultiError, or nil if none found.
func (m *ChatWithOtomoMessageToOtomoResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ChatWithOtomoMessageToOtomoResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetReply()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ChatWithOtomoMessageToOtomoResponseValidationError{
					field:  "Reply",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ChatWithOtomoMessageToOtomoResponseValidationError{
					field:  "Reply",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetReply()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ChatWithOtomoMessageToOtomoResponseValidationError{
				field:  "Reply",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ChatWithOtomoMessageToOtomoResponseMultiError(errors)
	}
	return nil
}

// ChatWithOtomoMessageToOtomoResponseMultiError is an error wrapping multiple
// validation errors returned by
// ChatWithOtomoMessageToOtomoResponse.ValidateAll() if the designated
// constraints aren't met.
type ChatWithOtomoMessageToOtomoResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChatWithOtomoMessageToOtomoResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChatWithOtomoMessageToOtomoResponseMultiError) AllErrors() []error { return m }

// ChatWithOtomoMessageToOtomoResponseValidationError is the validation error
// returned by ChatWithOtomoMessageToOtomoResponse.Validate if the designated
// constraints aren't met.
type ChatWithOtomoMessageToOtomoResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChatWithOtomoMessageToOtomoResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChatWithOtomoMessageToOtomoResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChatWithOtomoMessageToOtomoResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChatWithOtomoMessageToOtomoResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChatWithOtomoMessageToOtomoResponseValidationError) ErrorName() string {
	return "ChatWithOtomoMessageToOtomoResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ChatWithOtomoMessageToOtomoResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChatWithOtomoMessageToOtomoResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChatWithOtomoMessageToOtomoResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChatWithOtomoMessageToOtomoResponseValidationError{}
