// source: message.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var location_pb = require('./location_pb.js');
goog.object.extend(proto, location_pb);
goog.exportSymbol('proto.ExtractedPlace', null, global);
goog.exportSymbol('proto.GeocodedPlace', null, global);
goog.exportSymbol('proto.Message', null, global);
goog.exportSymbol('proto.MessageChunk', null, global);
goog.exportSymbol('proto.Place', null, global);
goog.exportSymbol('proto.PlaceDetails', null, global);
goog.exportSymbol('proto.PlaceDetailsStruct', null, global);
goog.exportSymbol('proto.PlaceExtraction', null, global);
goog.exportSymbol('proto.PlacesStruct', null, global);
goog.exportSymbol('proto.Role', null, global);
goog.exportSymbol('proto.RouteStruct', null, global);
goog.exportSymbol('proto.StructName', null, global);
goog.exportSymbol('proto.Structure', null, global);
goog.exportSymbol('proto.Structure.StructCase', null, global);
goog.exportSymbol('proto.StructureChunk', null, global);
goog.exportSymbol('proto.Transportation', null, global);
goog.exportSymbol('proto.Waypoint', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Message = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Message, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Message.displayName = 'proto.Message';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PlaceExtraction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PlaceExtraction.repeatedFields_, null);
};
goog.inherits(proto.PlaceExtraction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PlaceExtraction.displayName = 'proto.PlaceExtraction';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ExtractedPlace = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ExtractedPlace, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ExtractedPlace.displayName = 'proto.ExtractedPlace';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GeocodedPlace = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GeocodedPlace, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GeocodedPlace.displayName = 'proto.GeocodedPlace';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MessageChunk = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MessageChunk, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MessageChunk.displayName = 'proto.MessageChunk';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Structure = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.Structure.oneofGroups_);
};
goog.inherits(proto.Structure, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Structure.displayName = 'proto.Structure';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.StructureChunk = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.StructureChunk, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.StructureChunk.displayName = 'proto.StructureChunk';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PlaceDetailsStruct = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PlaceDetailsStruct, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PlaceDetailsStruct.displayName = 'proto.PlaceDetailsStruct';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PlaceDetails = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PlaceDetails, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PlaceDetails.displayName = 'proto.PlaceDetails';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PlacesStruct = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PlacesStruct.repeatedFields_, null);
};
goog.inherits(proto.PlacesStruct, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PlacesStruct.displayName = 'proto.PlacesStruct';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Place = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Place, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Place.displayName = 'proto.Place';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.RouteStruct = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.RouteStruct.repeatedFields_, null);
};
goog.inherits(proto.RouteStruct, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.RouteStruct.displayName = 'proto.RouteStruct';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Waypoint = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Waypoint.repeatedFields_, null);
};
goog.inherits(proto.Waypoint, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Waypoint.displayName = 'proto.Waypoint';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Message.prototype.toObject = function(opt_includeInstance) {
  return proto.Message.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Message} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Message.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    text: jspb.Message.getFieldWithDefault(msg, 2, ""),
    role: jspb.Message.getFieldWithDefault(msg, 3, 0),
    sentAt: (f = msg.getSentAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    clientId: (f = msg.getClientId()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    placeExtraction: (f = msg.getPlaceExtraction()) && proto.PlaceExtraction.toObject(includeInstance, f),
    content: jspb.Message.getFieldWithDefault(msg, 7, ""),
    structure: (f = msg.getStructure()) && proto.Structure.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Message}
 */
proto.Message.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Message;
  return proto.Message.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Message} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Message}
 */
proto.Message.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 3:
      var value = /** @type {!proto.Role} */ (reader.readEnum());
      msg.setRole(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setSentAt(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setClientId(value);
      break;
    case 6:
      var value = new proto.PlaceExtraction;
      reader.readMessage(value,proto.PlaceExtraction.deserializeBinaryFromReader);
      msg.setPlaceExtraction(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    case 8:
      var value = new proto.Structure;
      reader.readMessage(value,proto.Structure.deserializeBinaryFromReader);
      msg.setStructure(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Message.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Message.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Message} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Message.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRole();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getSentAt();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getClientId();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getPlaceExtraction();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.PlaceExtraction.serializeBinaryToWriter
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getStructure();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.Structure.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.Message.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string text = 2;
 * @return {string}
 */
proto.Message.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Role role = 3;
 * @return {!proto.Role}
 */
proto.Message.prototype.getRole = function() {
  return /** @type {!proto.Role} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.Role} value
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.setRole = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp sent_at = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.Message.prototype.getSentAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setSentAt = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearSentAt = function() {
  return this.setSentAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasSentAt = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.StringValue client_id = 5;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.Message.prototype.getClientId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 5));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setClientId = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearClientId = function() {
  return this.setClientId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasClientId = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional PlaceExtraction place_extraction = 6;
 * @return {?proto.PlaceExtraction}
 */
proto.Message.prototype.getPlaceExtraction = function() {
  return /** @type{?proto.PlaceExtraction} */ (
    jspb.Message.getWrapperField(this, proto.PlaceExtraction, 6));
};


/**
 * @param {?proto.PlaceExtraction|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setPlaceExtraction = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearPlaceExtraction = function() {
  return this.setPlaceExtraction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasPlaceExtraction = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string content = 7;
 * @return {string}
 */
proto.Message.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.setContent = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional Structure structure = 8;
 * @return {?proto.Structure}
 */
proto.Message.prototype.getStructure = function() {
  return /** @type{?proto.Structure} */ (
    jspb.Message.getWrapperField(this, proto.Structure, 8));
};


/**
 * @param {?proto.Structure|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setStructure = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearStructure = function() {
  return this.setStructure(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasStructure = function() {
  return jspb.Message.getField(this, 8) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PlaceExtraction.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PlaceExtraction.prototype.toObject = function(opt_includeInstance) {
  return proto.PlaceExtraction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PlaceExtraction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PlaceExtraction.toObject = function(includeInstance, msg) {
  var f, obj = {
    placesList: jspb.Message.toObjectList(msg.getPlacesList(),
    proto.ExtractedPlace.toObject, includeInstance),
    processedAt: (f = msg.getProcessedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    error: (f = msg.getError()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PlaceExtraction}
 */
proto.PlaceExtraction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PlaceExtraction;
  return proto.PlaceExtraction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PlaceExtraction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PlaceExtraction}
 */
proto.PlaceExtraction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ExtractedPlace;
      reader.readMessage(value,proto.ExtractedPlace.deserializeBinaryFromReader);
      msg.addPlaces(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setProcessedAt(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PlaceExtraction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PlaceExtraction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PlaceExtraction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PlaceExtraction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlacesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.ExtractedPlace.serializeBinaryToWriter
    );
  }
  f = message.getProcessedAt();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ExtractedPlace places = 1;
 * @return {!Array<!proto.ExtractedPlace>}
 */
proto.PlaceExtraction.prototype.getPlacesList = function() {
  return /** @type{!Array<!proto.ExtractedPlace>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ExtractedPlace, 1));
};


/**
 * @param {!Array<!proto.ExtractedPlace>} value
 * @return {!proto.PlaceExtraction} returns this
*/
proto.PlaceExtraction.prototype.setPlacesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.ExtractedPlace=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ExtractedPlace}
 */
proto.PlaceExtraction.prototype.addPlaces = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.ExtractedPlace, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PlaceExtraction} returns this
 */
proto.PlaceExtraction.prototype.clearPlacesList = function() {
  return this.setPlacesList([]);
};


/**
 * optional google.protobuf.Timestamp processed_at = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.PlaceExtraction.prototype.getProcessedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.PlaceExtraction} returns this
*/
proto.PlaceExtraction.prototype.setProcessedAt = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.PlaceExtraction} returns this
 */
proto.PlaceExtraction.prototype.clearProcessedAt = function() {
  return this.setProcessedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.PlaceExtraction.prototype.hasProcessedAt = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.StringValue error = 3;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.PlaceExtraction.prototype.getError = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 3));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.PlaceExtraction} returns this
*/
proto.PlaceExtraction.prototype.setError = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.PlaceExtraction} returns this
 */
proto.PlaceExtraction.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.PlaceExtraction.prototype.hasError = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ExtractedPlace.prototype.toObject = function(opt_includeInstance) {
  return proto.ExtractedPlace.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ExtractedPlace} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ExtractedPlace.toObject = function(includeInstance, msg) {
  var f, obj = {
    text: jspb.Message.getFieldWithDefault(msg, 1, ""),
    geocodedPlace: (f = msg.getGeocodedPlace()) && proto.GeocodedPlace.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ExtractedPlace}
 */
proto.ExtractedPlace.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ExtractedPlace;
  return proto.ExtractedPlace.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ExtractedPlace} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ExtractedPlace}
 */
proto.ExtractedPlace.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 2:
      var value = new proto.GeocodedPlace;
      reader.readMessage(value,proto.GeocodedPlace.deserializeBinaryFromReader);
      msg.setGeocodedPlace(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ExtractedPlace.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ExtractedPlace.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ExtractedPlace} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ExtractedPlace.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getGeocodedPlace();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.GeocodedPlace.serializeBinaryToWriter
    );
  }
};


/**
 * optional string text = 1;
 * @return {string}
 */
proto.ExtractedPlace.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ExtractedPlace} returns this
 */
proto.ExtractedPlace.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional GeocodedPlace geocoded_place = 2;
 * @return {?proto.GeocodedPlace}
 */
proto.ExtractedPlace.prototype.getGeocodedPlace = function() {
  return /** @type{?proto.GeocodedPlace} */ (
    jspb.Message.getWrapperField(this, proto.GeocodedPlace, 2));
};


/**
 * @param {?proto.GeocodedPlace|undefined} value
 * @return {!proto.ExtractedPlace} returns this
*/
proto.ExtractedPlace.prototype.setGeocodedPlace = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ExtractedPlace} returns this
 */
proto.ExtractedPlace.prototype.clearGeocodedPlace = function() {
  return this.setGeocodedPlace(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ExtractedPlace.prototype.hasGeocodedPlace = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GeocodedPlace.prototype.toObject = function(opt_includeInstance) {
  return proto.GeocodedPlace.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GeocodedPlace} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GeocodedPlace.toObject = function(includeInstance, msg) {
  var f, obj = {
    googlePlaceId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    latLng: (f = msg.getLatLng()) && location_pb.LatLng.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GeocodedPlace}
 */
proto.GeocodedPlace.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GeocodedPlace;
  return proto.GeocodedPlace.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GeocodedPlace} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GeocodedPlace}
 */
proto.GeocodedPlace.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setGooglePlaceId(value);
      break;
    case 2:
      var value = new location_pb.LatLng;
      reader.readMessage(value,location_pb.LatLng.deserializeBinaryFromReader);
      msg.setLatLng(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GeocodedPlace.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GeocodedPlace.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GeocodedPlace} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GeocodedPlace.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGooglePlaceId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLatLng();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      location_pb.LatLng.serializeBinaryToWriter
    );
  }
};


/**
 * optional string google_place_id = 1;
 * @return {string}
 */
proto.GeocodedPlace.prototype.getGooglePlaceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.GeocodedPlace} returns this
 */
proto.GeocodedPlace.prototype.setGooglePlaceId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional LatLng lat_lng = 2;
 * @return {?proto.LatLng}
 */
proto.GeocodedPlace.prototype.getLatLng = function() {
  return /** @type{?proto.LatLng} */ (
    jspb.Message.getWrapperField(this, location_pb.LatLng, 2));
};


/**
 * @param {?proto.LatLng|undefined} value
 * @return {!proto.GeocodedPlace} returns this
*/
proto.GeocodedPlace.prototype.setLatLng = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.GeocodedPlace} returns this
 */
proto.GeocodedPlace.prototype.clearLatLng = function() {
  return this.setLatLng(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.GeocodedPlace.prototype.hasLatLng = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MessageChunk.prototype.toObject = function(opt_includeInstance) {
  return proto.MessageChunk.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MessageChunk} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MessageChunk.toObject = function(includeInstance, msg) {
  var f, obj = {
    messageId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    text: jspb.Message.getFieldWithDefault(msg, 2, ""),
    role: jspb.Message.getFieldWithDefault(msg, 3, 0),
    sentAt: (f = msg.getSentAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    clientId: (f = msg.getClientId()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    isLast: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    content: jspb.Message.getFieldWithDefault(msg, 7, ""),
    structure: (f = msg.getStructure()) && proto.StructureChunk.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MessageChunk}
 */
proto.MessageChunk.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MessageChunk;
  return proto.MessageChunk.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MessageChunk} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MessageChunk}
 */
proto.MessageChunk.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessageId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 3:
      var value = /** @type {!proto.Role} */ (reader.readEnum());
      msg.setRole(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setSentAt(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setClientId(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsLast(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    case 8:
      var value = new proto.StructureChunk;
      reader.readMessage(value,proto.StructureChunk.deserializeBinaryFromReader);
      msg.setStructure(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MessageChunk.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MessageChunk.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MessageChunk} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MessageChunk.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessageId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRole();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getSentAt();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getClientId();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getIsLast();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getStructure();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.StructureChunk.serializeBinaryToWriter
    );
  }
};


/**
 * optional string message_id = 1;
 * @return {string}
 */
proto.MessageChunk.prototype.getMessageId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.MessageChunk} returns this
 */
proto.MessageChunk.prototype.setMessageId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string text = 2;
 * @return {string}
 */
proto.MessageChunk.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.MessageChunk} returns this
 */
proto.MessageChunk.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Role role = 3;
 * @return {!proto.Role}
 */
proto.MessageChunk.prototype.getRole = function() {
  return /** @type {!proto.Role} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.Role} value
 * @return {!proto.MessageChunk} returns this
 */
proto.MessageChunk.prototype.setRole = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp sent_at = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.MessageChunk.prototype.getSentAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.MessageChunk} returns this
*/
proto.MessageChunk.prototype.setSentAt = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.MessageChunk} returns this
 */
proto.MessageChunk.prototype.clearSentAt = function() {
  return this.setSentAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.MessageChunk.prototype.hasSentAt = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.StringValue client_id = 5;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.MessageChunk.prototype.getClientId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 5));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.MessageChunk} returns this
*/
proto.MessageChunk.prototype.setClientId = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.MessageChunk} returns this
 */
proto.MessageChunk.prototype.clearClientId = function() {
  return this.setClientId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.MessageChunk.prototype.hasClientId = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bool is_last = 6;
 * @return {boolean}
 */
proto.MessageChunk.prototype.getIsLast = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.MessageChunk} returns this
 */
proto.MessageChunk.prototype.setIsLast = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional string content = 7;
 * @return {string}
 */
proto.MessageChunk.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.MessageChunk} returns this
 */
proto.MessageChunk.prototype.setContent = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional StructureChunk structure = 8;
 * @return {?proto.StructureChunk}
 */
proto.MessageChunk.prototype.getStructure = function() {
  return /** @type{?proto.StructureChunk} */ (
    jspb.Message.getWrapperField(this, proto.StructureChunk, 8));
};


/**
 * @param {?proto.StructureChunk|undefined} value
 * @return {!proto.MessageChunk} returns this
*/
proto.MessageChunk.prototype.setStructure = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.MessageChunk} returns this
 */
proto.MessageChunk.prototype.clearStructure = function() {
  return this.setStructure(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.MessageChunk.prototype.hasStructure = function() {
  return jspb.Message.getField(this, 8) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.Structure.oneofGroups_ = [[2,3,4]];

/**
 * @enum {number}
 */
proto.Structure.StructCase = {
  STRUCT_NOT_SET: 0,
  PLACE_DETAILS_STRUCT: 2,
  PLACES_STRUCT: 3,
  ROUTE_STRUCT: 4
};

/**
 * @return {proto.Structure.StructCase}
 */
proto.Structure.prototype.getStructCase = function() {
  return /** @type {proto.Structure.StructCase} */(jspb.Message.computeOneofCase(this, proto.Structure.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Structure.prototype.toObject = function(opt_includeInstance) {
  return proto.Structure.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Structure} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Structure.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, 0),
    placeDetailsStruct: (f = msg.getPlaceDetailsStruct()) && proto.PlaceDetailsStruct.toObject(includeInstance, f),
    placesStruct: (f = msg.getPlacesStruct()) && proto.PlacesStruct.toObject(includeInstance, f),
    routeStruct: (f = msg.getRouteStruct()) && proto.RouteStruct.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Structure}
 */
proto.Structure.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Structure;
  return proto.Structure.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Structure} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Structure}
 */
proto.Structure.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.StructName} */ (reader.readEnum());
      msg.setName(value);
      break;
    case 2:
      var value = new proto.PlaceDetailsStruct;
      reader.readMessage(value,proto.PlaceDetailsStruct.deserializeBinaryFromReader);
      msg.setPlaceDetailsStruct(value);
      break;
    case 3:
      var value = new proto.PlacesStruct;
      reader.readMessage(value,proto.PlacesStruct.deserializeBinaryFromReader);
      msg.setPlacesStruct(value);
      break;
    case 4:
      var value = new proto.RouteStruct;
      reader.readMessage(value,proto.RouteStruct.deserializeBinaryFromReader);
      msg.setRouteStruct(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Structure.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Structure.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Structure} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Structure.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getPlaceDetailsStruct();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.PlaceDetailsStruct.serializeBinaryToWriter
    );
  }
  f = message.getPlacesStruct();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.PlacesStruct.serializeBinaryToWriter
    );
  }
  f = message.getRouteStruct();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.RouteStruct.serializeBinaryToWriter
    );
  }
};


/**
 * optional StructName name = 1;
 * @return {!proto.StructName}
 */
proto.Structure.prototype.getName = function() {
  return /** @type {!proto.StructName} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.StructName} value
 * @return {!proto.Structure} returns this
 */
proto.Structure.prototype.setName = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional PlaceDetailsStruct place_details_struct = 2;
 * @return {?proto.PlaceDetailsStruct}
 */
proto.Structure.prototype.getPlaceDetailsStruct = function() {
  return /** @type{?proto.PlaceDetailsStruct} */ (
    jspb.Message.getWrapperField(this, proto.PlaceDetailsStruct, 2));
};


/**
 * @param {?proto.PlaceDetailsStruct|undefined} value
 * @return {!proto.Structure} returns this
*/
proto.Structure.prototype.setPlaceDetailsStruct = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.Structure.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Structure} returns this
 */
proto.Structure.prototype.clearPlaceDetailsStruct = function() {
  return this.setPlaceDetailsStruct(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Structure.prototype.hasPlaceDetailsStruct = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional PlacesStruct places_struct = 3;
 * @return {?proto.PlacesStruct}
 */
proto.Structure.prototype.getPlacesStruct = function() {
  return /** @type{?proto.PlacesStruct} */ (
    jspb.Message.getWrapperField(this, proto.PlacesStruct, 3));
};


/**
 * @param {?proto.PlacesStruct|undefined} value
 * @return {!proto.Structure} returns this
*/
proto.Structure.prototype.setPlacesStruct = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.Structure.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Structure} returns this
 */
proto.Structure.prototype.clearPlacesStruct = function() {
  return this.setPlacesStruct(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Structure.prototype.hasPlacesStruct = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional RouteStruct route_struct = 4;
 * @return {?proto.RouteStruct}
 */
proto.Structure.prototype.getRouteStruct = function() {
  return /** @type{?proto.RouteStruct} */ (
    jspb.Message.getWrapperField(this, proto.RouteStruct, 4));
};


/**
 * @param {?proto.RouteStruct|undefined} value
 * @return {!proto.Structure} returns this
*/
proto.Structure.prototype.setRouteStruct = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.Structure.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Structure} returns this
 */
proto.Structure.prototype.clearRouteStruct = function() {
  return this.setRouteStruct(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Structure.prototype.hasRouteStruct = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.StructureChunk.prototype.toObject = function(opt_includeInstance) {
  return proto.StructureChunk.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.StructureChunk} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.StructureChunk.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, 0),
    struct: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.StructureChunk}
 */
proto.StructureChunk.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.StructureChunk;
  return proto.StructureChunk.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.StructureChunk} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.StructureChunk}
 */
proto.StructureChunk.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.StructName} */ (reader.readEnum());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStruct(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.StructureChunk.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.StructureChunk.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.StructureChunk} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.StructureChunk.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getStruct();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional StructName name = 1;
 * @return {!proto.StructName}
 */
proto.StructureChunk.prototype.getName = function() {
  return /** @type {!proto.StructName} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.StructName} value
 * @return {!proto.StructureChunk} returns this
 */
proto.StructureChunk.prototype.setName = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string struct = 2;
 * @return {string}
 */
proto.StructureChunk.prototype.getStruct = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.StructureChunk} returns this
 */
proto.StructureChunk.prototype.setStruct = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PlaceDetailsStruct.prototype.toObject = function(opt_includeInstance) {
  return proto.PlaceDetailsStruct.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PlaceDetailsStruct} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PlaceDetailsStruct.toObject = function(includeInstance, msg) {
  var f, obj = {
    prologue: jspb.Message.getFieldWithDefault(msg, 1, ""),
    details: (f = msg.getDetails()) && proto.PlaceDetails.toObject(includeInstance, f),
    epilogue: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PlaceDetailsStruct}
 */
proto.PlaceDetailsStruct.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PlaceDetailsStruct;
  return proto.PlaceDetailsStruct.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PlaceDetailsStruct} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PlaceDetailsStruct}
 */
proto.PlaceDetailsStruct.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrologue(value);
      break;
    case 2:
      var value = new proto.PlaceDetails;
      reader.readMessage(value,proto.PlaceDetails.deserializeBinaryFromReader);
      msg.setDetails(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEpilogue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PlaceDetailsStruct.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PlaceDetailsStruct.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PlaceDetailsStruct} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PlaceDetailsStruct.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPrologue();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDetails();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.PlaceDetails.serializeBinaryToWriter
    );
  }
  f = message.getEpilogue();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string prologue = 1;
 * @return {string}
 */
proto.PlaceDetailsStruct.prototype.getPrologue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.PlaceDetailsStruct} returns this
 */
proto.PlaceDetailsStruct.prototype.setPrologue = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional PlaceDetails details = 2;
 * @return {?proto.PlaceDetails}
 */
proto.PlaceDetailsStruct.prototype.getDetails = function() {
  return /** @type{?proto.PlaceDetails} */ (
    jspb.Message.getWrapperField(this, proto.PlaceDetails, 2));
};


/**
 * @param {?proto.PlaceDetails|undefined} value
 * @return {!proto.PlaceDetailsStruct} returns this
*/
proto.PlaceDetailsStruct.prototype.setDetails = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.PlaceDetailsStruct} returns this
 */
proto.PlaceDetailsStruct.prototype.clearDetails = function() {
  return this.setDetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.PlaceDetailsStruct.prototype.hasDetails = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string epilogue = 3;
 * @return {string}
 */
proto.PlaceDetailsStruct.prototype.getEpilogue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.PlaceDetailsStruct} returns this
 */
proto.PlaceDetailsStruct.prototype.setEpilogue = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PlaceDetails.prototype.toObject = function(opt_includeInstance) {
  return proto.PlaceDetails.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PlaceDetails} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PlaceDetails.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    description: jspb.Message.getFieldWithDefault(msg, 2, ""),
    geocodedPlace: (f = msg.getGeocodedPlace()) && proto.GeocodedPlace.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PlaceDetails}
 */
proto.PlaceDetails.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PlaceDetails;
  return proto.PlaceDetails.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PlaceDetails} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PlaceDetails}
 */
proto.PlaceDetails.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 3:
      var value = new proto.GeocodedPlace;
      reader.readMessage(value,proto.GeocodedPlace.deserializeBinaryFromReader);
      msg.setGeocodedPlace(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PlaceDetails.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PlaceDetails.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PlaceDetails} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PlaceDetails.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getGeocodedPlace();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.GeocodedPlace.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.PlaceDetails.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.PlaceDetails} returns this
 */
proto.PlaceDetails.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string description = 2;
 * @return {string}
 */
proto.PlaceDetails.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.PlaceDetails} returns this
 */
proto.PlaceDetails.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional GeocodedPlace geocoded_place = 3;
 * @return {?proto.GeocodedPlace}
 */
proto.PlaceDetails.prototype.getGeocodedPlace = function() {
  return /** @type{?proto.GeocodedPlace} */ (
    jspb.Message.getWrapperField(this, proto.GeocodedPlace, 3));
};


/**
 * @param {?proto.GeocodedPlace|undefined} value
 * @return {!proto.PlaceDetails} returns this
*/
proto.PlaceDetails.prototype.setGeocodedPlace = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.PlaceDetails} returns this
 */
proto.PlaceDetails.prototype.clearGeocodedPlace = function() {
  return this.setGeocodedPlace(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.PlaceDetails.prototype.hasGeocodedPlace = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PlacesStruct.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PlacesStruct.prototype.toObject = function(opt_includeInstance) {
  return proto.PlacesStruct.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PlacesStruct} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PlacesStruct.toObject = function(includeInstance, msg) {
  var f, obj = {
    prologue: jspb.Message.getFieldWithDefault(msg, 1, ""),
    placesList: jspb.Message.toObjectList(msg.getPlacesList(),
    proto.Place.toObject, includeInstance),
    epilogue: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PlacesStruct}
 */
proto.PlacesStruct.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PlacesStruct;
  return proto.PlacesStruct.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PlacesStruct} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PlacesStruct}
 */
proto.PlacesStruct.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrologue(value);
      break;
    case 2:
      var value = new proto.Place;
      reader.readMessage(value,proto.Place.deserializeBinaryFromReader);
      msg.addPlaces(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEpilogue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PlacesStruct.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PlacesStruct.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PlacesStruct} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PlacesStruct.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPrologue();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPlacesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.Place.serializeBinaryToWriter
    );
  }
  f = message.getEpilogue();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string prologue = 1;
 * @return {string}
 */
proto.PlacesStruct.prototype.getPrologue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.PlacesStruct} returns this
 */
proto.PlacesStruct.prototype.setPrologue = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Place places = 2;
 * @return {!Array<!proto.Place>}
 */
proto.PlacesStruct.prototype.getPlacesList = function() {
  return /** @type{!Array<!proto.Place>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Place, 2));
};


/**
 * @param {!Array<!proto.Place>} value
 * @return {!proto.PlacesStruct} returns this
*/
proto.PlacesStruct.prototype.setPlacesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.Place=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Place}
 */
proto.PlacesStruct.prototype.addPlaces = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.Place, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PlacesStruct} returns this
 */
proto.PlacesStruct.prototype.clearPlacesList = function() {
  return this.setPlacesList([]);
};


/**
 * optional string epilogue = 3;
 * @return {string}
 */
proto.PlacesStruct.prototype.getEpilogue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.PlacesStruct} returns this
 */
proto.PlacesStruct.prototype.setEpilogue = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Place.prototype.toObject = function(opt_includeInstance) {
  return proto.Place.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Place} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Place.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    description: jspb.Message.getFieldWithDefault(msg, 2, ""),
    geocodedPlace: (f = msg.getGeocodedPlace()) && proto.GeocodedPlace.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Place}
 */
proto.Place.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Place;
  return proto.Place.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Place} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Place}
 */
proto.Place.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 3:
      var value = new proto.GeocodedPlace;
      reader.readMessage(value,proto.GeocodedPlace.deserializeBinaryFromReader);
      msg.setGeocodedPlace(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Place.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Place.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Place} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Place.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getGeocodedPlace();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.GeocodedPlace.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.Place.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Place} returns this
 */
proto.Place.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string description = 2;
 * @return {string}
 */
proto.Place.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Place} returns this
 */
proto.Place.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional GeocodedPlace geocoded_place = 3;
 * @return {?proto.GeocodedPlace}
 */
proto.Place.prototype.getGeocodedPlace = function() {
  return /** @type{?proto.GeocodedPlace} */ (
    jspb.Message.getWrapperField(this, proto.GeocodedPlace, 3));
};


/**
 * @param {?proto.GeocodedPlace|undefined} value
 * @return {!proto.Place} returns this
*/
proto.Place.prototype.setGeocodedPlace = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Place} returns this
 */
proto.Place.prototype.clearGeocodedPlace = function() {
  return this.setGeocodedPlace(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Place.prototype.hasGeocodedPlace = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.RouteStruct.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.RouteStruct.prototype.toObject = function(opt_includeInstance) {
  return proto.RouteStruct.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.RouteStruct} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.RouteStruct.toObject = function(includeInstance, msg) {
  var f, obj = {
    prologue: jspb.Message.getFieldWithDefault(msg, 1, ""),
    waypointsList: jspb.Message.toObjectList(msg.getWaypointsList(),
    proto.Waypoint.toObject, includeInstance),
    epilogue: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.RouteStruct}
 */
proto.RouteStruct.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.RouteStruct;
  return proto.RouteStruct.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.RouteStruct} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.RouteStruct}
 */
proto.RouteStruct.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrologue(value);
      break;
    case 2:
      var value = new proto.Waypoint;
      reader.readMessage(value,proto.Waypoint.deserializeBinaryFromReader);
      msg.addWaypoints(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEpilogue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.RouteStruct.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.RouteStruct.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.RouteStruct} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.RouteStruct.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPrologue();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getWaypointsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.Waypoint.serializeBinaryToWriter
    );
  }
  f = message.getEpilogue();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string prologue = 1;
 * @return {string}
 */
proto.RouteStruct.prototype.getPrologue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.RouteStruct} returns this
 */
proto.RouteStruct.prototype.setPrologue = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Waypoint waypoints = 2;
 * @return {!Array<!proto.Waypoint>}
 */
proto.RouteStruct.prototype.getWaypointsList = function() {
  return /** @type{!Array<!proto.Waypoint>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Waypoint, 2));
};


/**
 * @param {!Array<!proto.Waypoint>} value
 * @return {!proto.RouteStruct} returns this
*/
proto.RouteStruct.prototype.setWaypointsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.Waypoint=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Waypoint}
 */
proto.RouteStruct.prototype.addWaypoints = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.Waypoint, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.RouteStruct} returns this
 */
proto.RouteStruct.prototype.clearWaypointsList = function() {
  return this.setWaypointsList([]);
};


/**
 * optional string epilogue = 3;
 * @return {string}
 */
proto.RouteStruct.prototype.getEpilogue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.RouteStruct} returns this
 */
proto.RouteStruct.prototype.setEpilogue = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Waypoint.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Waypoint.prototype.toObject = function(opt_includeInstance) {
  return proto.Waypoint.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Waypoint} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Waypoint.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    description: jspb.Message.getFieldWithDefault(msg, 2, ""),
    transportationList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    transportationDescription: jspb.Message.getFieldWithDefault(msg, 4, ""),
    geocodedPlace: (f = msg.getGeocodedPlace()) && proto.GeocodedPlace.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Waypoint}
 */
proto.Waypoint.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Waypoint;
  return proto.Waypoint.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Waypoint} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Waypoint}
 */
proto.Waypoint.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 3:
      var values = /** @type {!Array<!proto.Transportation>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addTransportation(values[i]);
      }
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransportationDescription(value);
      break;
    case 5:
      var value = new proto.GeocodedPlace;
      reader.readMessage(value,proto.GeocodedPlace.deserializeBinaryFromReader);
      msg.setGeocodedPlace(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Waypoint.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Waypoint.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Waypoint} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Waypoint.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTransportationList();
  if (f.length > 0) {
    writer.writePackedEnum(
      3,
      f
    );
  }
  f = message.getTransportationDescription();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getGeocodedPlace();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.GeocodedPlace.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.Waypoint.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Waypoint} returns this
 */
proto.Waypoint.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string description = 2;
 * @return {string}
 */
proto.Waypoint.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Waypoint} returns this
 */
proto.Waypoint.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated Transportation transportation = 3;
 * @return {!Array<!proto.Transportation>}
 */
proto.Waypoint.prototype.getTransportationList = function() {
  return /** @type {!Array<!proto.Transportation>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<!proto.Transportation>} value
 * @return {!proto.Waypoint} returns this
 */
proto.Waypoint.prototype.setTransportationList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {!proto.Transportation} value
 * @param {number=} opt_index
 * @return {!proto.Waypoint} returns this
 */
proto.Waypoint.prototype.addTransportation = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Waypoint} returns this
 */
proto.Waypoint.prototype.clearTransportationList = function() {
  return this.setTransportationList([]);
};


/**
 * optional string transportation_description = 4;
 * @return {string}
 */
proto.Waypoint.prototype.getTransportationDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Waypoint} returns this
 */
proto.Waypoint.prototype.setTransportationDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional GeocodedPlace geocoded_place = 5;
 * @return {?proto.GeocodedPlace}
 */
proto.Waypoint.prototype.getGeocodedPlace = function() {
  return /** @type{?proto.GeocodedPlace} */ (
    jspb.Message.getWrapperField(this, proto.GeocodedPlace, 5));
};


/**
 * @param {?proto.GeocodedPlace|undefined} value
 * @return {!proto.Waypoint} returns this
*/
proto.Waypoint.prototype.setGeocodedPlace = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Waypoint} returns this
 */
proto.Waypoint.prototype.clearGeocodedPlace = function() {
  return this.setGeocodedPlace(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Waypoint.prototype.hasGeocodedPlace = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * @enum {number}
 */
proto.Role = {
  ROLE_UNKNOWN: 0,
  USER: 1,
  OTOMO: 2
};

/**
 * @enum {number}
 */
proto.StructName = {
  STRUCT_NAME_UNKNOWN: 0,
  PLACE_DETAILS: 1,
  PLACES: 2,
  ROUTE: 3
};

/**
 * @enum {number}
 */
proto.Transportation = {
  TRANSPORTATION_UNKNOWN: 0,
  TRAIN: 1,
  AIRPLANE: 2,
  CAR: 3,
  SHIP: 4,
  BUS: 5,
  BICYCLE: 6,
  MOTORCYCLE: 7,
  WALKING: 8,
  TAXI: 9,
  OTHER: 10
};

goog.object.extend(exports, proto);
