/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 4.23.4
 * source: message.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./google/protobuf/timestamp";
import * as dependency_2 from "./google/protobuf/wrappers";
import * as pb_1 from "google-protobuf";
export enum Role {
    UNKNOWN = 0,
    USER = 1,
    OTOMO = 2
}
export class Message extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        id?: string;
        text?: string;
        role?: Role;
        sent_at?: dependency_1.google.protobuf.Timestamp;
        client_id?: dependency_2.google.protobuf.StringValue;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("id" in data && data.id != undefined) {
                this.id = data.id;
            }
            if ("text" in data && data.text != undefined) {
                this.text = data.text;
            }
            if ("role" in data && data.role != undefined) {
                this.role = data.role;
            }
            if ("sent_at" in data && data.sent_at != undefined) {
                this.sent_at = data.sent_at;
            }
            if ("client_id" in data && data.client_id != undefined) {
                this.client_id = data.client_id;
            }
        }
    }
    get id() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set id(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get text() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set text(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get role() {
        return pb_1.Message.getFieldWithDefault(this, 3, Role.UNKNOWN) as Role;
    }
    set role(value: Role) {
        pb_1.Message.setField(this, 3, value);
    }
    get sent_at() {
        return pb_1.Message.getWrapperField(this, dependency_1.google.protobuf.Timestamp, 4) as dependency_1.google.protobuf.Timestamp;
    }
    set sent_at(value: dependency_1.google.protobuf.Timestamp) {
        pb_1.Message.setWrapperField(this, 4, value);
    }
    get has_sent_at() {
        return pb_1.Message.getField(this, 4) != null;
    }
    get client_id() {
        return pb_1.Message.getWrapperField(this, dependency_2.google.protobuf.StringValue, 5) as dependency_2.google.protobuf.StringValue;
    }
    set client_id(value: dependency_2.google.protobuf.StringValue) {
        pb_1.Message.setWrapperField(this, 5, value);
    }
    get has_client_id() {
        return pb_1.Message.getField(this, 5) != null;
    }
    static fromObject(data: {
        id?: string;
        text?: string;
        role?: Role;
        sent_at?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
        client_id?: ReturnType<typeof dependency_2.google.protobuf.StringValue.prototype.toObject>;
    }): Message {
        const message = new Message({});
        if (data.id != null) {
            message.id = data.id;
        }
        if (data.text != null) {
            message.text = data.text;
        }
        if (data.role != null) {
            message.role = data.role;
        }
        if (data.sent_at != null) {
            message.sent_at = dependency_1.google.protobuf.Timestamp.fromObject(data.sent_at);
        }
        if (data.client_id != null) {
            message.client_id = dependency_2.google.protobuf.StringValue.fromObject(data.client_id);
        }
        return message;
    }
    toObject() {
        const data: {
            id?: string;
            text?: string;
            role?: Role;
            sent_at?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            client_id?: ReturnType<typeof dependency_2.google.protobuf.StringValue.prototype.toObject>;
        } = {};
        if (this.id != null) {
            data.id = this.id;
        }
        if (this.text != null) {
            data.text = this.text;
        }
        if (this.role != null) {
            data.role = this.role;
        }
        if (this.sent_at != null) {
            data.sent_at = this.sent_at.toObject();
        }
        if (this.client_id != null) {
            data.client_id = this.client_id.toObject();
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.id.length)
            writer.writeString(1, this.id);
        if (this.text.length)
            writer.writeString(2, this.text);
        if (this.role != Role.UNKNOWN)
            writer.writeEnum(3, this.role);
        if (this.has_sent_at)
            writer.writeMessage(4, this.sent_at, () => this.sent_at.serialize(writer));
        if (this.has_client_id)
            writer.writeMessage(5, this.client_id, () => this.client_id.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Message {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Message();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.id = reader.readString();
                    break;
                case 2:
                    message.text = reader.readString();
                    break;
                case 3:
                    message.role = reader.readEnum();
                    break;
                case 4:
                    reader.readMessage(message.sent_at, () => message.sent_at = dependency_1.google.protobuf.Timestamp.deserialize(reader));
                    break;
                case 5:
                    reader.readMessage(message.client_id, () => message.client_id = dependency_2.google.protobuf.StringValue.deserialize(reader));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): Message {
        return Message.deserialize(bytes);
    }
}
