// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDafQyk9I9quRjw685FgT5xqfYM9cKIZqo',
    appId: '1:124184920709:web:661f1dbccb3e9c8d06dfec',
    messagingSenderId: '124184920709',
    projectId: 'otomo-401310',
    authDomain: 'otomo-401310.firebaseapp.com',
    storageBucket: 'otomo-401310.appspot.com',
    measurementId: 'G-DBZLNCB2VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4DZfLN_VdGNac0R_rDB49VpLQ7BDU2yE',
    appId: '1:124184920709:android:83c8b816b04412c906dfec',
    messagingSenderId: '124184920709',
    projectId: 'otomo-401310',
    storageBucket: 'otomo-401310.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZoaDG7u1JNM4ApIzB2rckZRR-AKMCwj8',
    appId: '1:124184920709:ios:a8a08b4d7982f91706dfec',
    messagingSenderId: '124184920709',
    projectId: 'otomo-401310',
    storageBucket: 'otomo-401310.appspot.com',
    iosClientId: '124184920709-sqs9i8qdjdc1mrl3cftp4541a0cp3f7n.apps.googleusercontent.com',
    iosBundleId: 'com.sh0o0.otomo',
  );
}
