gcp_project_id         = "otomo-dev-401306"
load_balancer_name     = "api"
region                 = "us-west1"
api_domain             = "otomo-dev"
cloud_run_service_name = "api"
cloud_run_image_name   = "api"
slack_channel_name     = "otomo-dev"
