FROM golang:alpine

RUN apk update &&  apk add git
RUN go install github.com/cosmtrek/air@latest
RUN go install github.com/go-delve/delve/cmd/dlv@latest

COPY . /app
WORKDIR /app

RUN go mod download

CMD air -c .air.toml
